name: Staging translated Qiskit docs

on:
  pull_request:
    branches: [ master ]
  label:
     types: [ gh-pages-main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_docs:
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'gh-pages-main' )
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U virtualenv 'setuptools<61.0.0' wheel
        pip install -U -r requirements-dev.txt sphinx-intl qiskit
        pip install -c constraints.txt -U jupyter sphinx nbsphinx networkx sphinx_rtd_theme qiskit-terra[visualization] cvxpy 'pyscf<1.7.4'
        pip install -c constraints.txt -U .
        sudo apt-get install graphviz pandoc

    - name: Build translated Qiskit Docs
      env:
        TRANSLATION_LANG: ${{ matrix.language }}
      run: |
        tools/staging_translated_documentation.sh

    - name: Compress artifact
      run: |
        mkdir artifacts
        cp -R build/locale/* build/
        rm -r build/locale
        tar -zcvf translated_docs_${{matrix.language}}.tar.gz build/
        mv translated_docs_${{matrix.language}}.tar.gz artifacts/.

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./artifacts
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: qiskit-translated-docs
        path: artifacts

    strategy:
      matrix:
        language:
          - bn_BN
          # - de_DE
          # - el_GR
          # - es_UN
          # - fr_FR
          # - hi_IN
          # - id_ID
          # - it_IT
          # - ja_JP
          # - ko_KR
          # - ml_IN
          # - mr_IN
          # - pl_PL
          # - pt_UN
          # - ru_RU
          # - sw_KE
          # - ta_IN
          # - th_TH
          # - tr_TR
          # - vi_VN
          # - zh_CN
          # - zh_TW

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  # deploy_docs:
  #   runs-on: ubuntu-latest
  #   needs: build_docs
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Download artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: qiskit-translated-docs
  #   - name: Decompress artifact
  #     run: |
  #       for f in *.tar.gz; do tar -xvf "$f"; done
  #   - name: Push directory to another repository
  #     uses: cpina/github-action-push-to-another-repository@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.STAGING_REPO }}
  #     with:
  #       source-directory: 'build'
  #       destination-github-username: 'qiskit-community'
  #       destination-repository-name: 'qiskit-translations-staging'
  #       target-directory: 'docs'
  #       user-name: SooluThomas
  #       user-email: 11485594+SooluThomas@users.noreply.github.com
  #       target-branch: main
  #       commit-message: Qiskit Autodeploy ORIGIN_COMMIT from $GITHUB_REF
